.\" Manpage for guidedog.
.\" Contact digiplan.pt@gmail.com to correct errors or typos.
.TH man 8 "27 Jan 2015" "1.2.0" "guidedog man page"
.SH NAME
guidedog \- NAT/masquerading/port-forwarding configuration tool
.SH SYNOPSIS
guidedog
.SH DESCRIPTION
Guidedog is an utility to easily activate and configure your machine for packet routing, Network Address Translation/IP Masquerading (NAT) and port-forwarding.
.br
Guidedog is expected to run with superuser privileges. If not, you can import or export configuration files, but you are not allowed to actually apply them.
.SH OPTIONS
The guidedog does not take any options.
.SH SEE ALSO
iptables(8)
.SH BUGS
No known bugs.
.SH "SEE ALSO"
https://github.com/antocm/guidedog/wiki
